---
name: WWW-Sucksub-Divxstation
version: 0.02
author: Timothée Foucart <timothee.foucart@apinc.org>
abstract: automated access to divxstation.com
license: perl
requires:
  Carp: >= 1.0
  DB_File: >= 1.8
  HTTP::Cookies: >= 1.3
  Test::More: >=0.5
  WWW::Mechanize: >= 1.02
provides:
  WWW::Sucksub::Divxstation:
    file: lib/WWW/Sucksub/Divxstation.pm
    version: 0.02
generated_by: Module::Build version 0.25
